Full rewrite

diff --git a/gomake b/gomake
--- a/gomake
+++ b/gomake
@@ -1,6 +1,36 @@
 #!/bin/bash
-# this is a script to build go apps
 set -e
+
+ : ${target_name:=dist}
+ : ${work_path:=.}
+ : ${app:=$(basename $(cd "${work_path}"; pwd))}
+ : ${repo:=$(git config --get remote.origin.url | sed -n 's/.*@\(.*\)\.git/\1/p' | tr : /)}
+ : ${osarchi:="$(go env GOHOSTOS)-$(go env GOHOSTARCH)"}
+ : ${release_osarchi:="linux-amd64,darwin-amd64,windows-amd64"}
+ : ${version:=0}
+ : ${access_token:=}
+ : ${upx:=}
+
+read -d '' helper <<EOF || true
+Usage: gomake [-v version][-t token] command...
+  gomake is a script to build go apps
+
+  command
+      clean                 clean '${target_name}/' directory
+      build                 build (current platform only by default)
+      quality               Format, Fix, check error handled, lint, vet, misspell, ineffassign, Gocyclo
+      test                  run go tests
+      release               clean, build all platform, test, check git is clean, tag, push tag & build ZIPs
+      gomake_update         self updating by downloading and replacing with latest version
+
+         default is 'clean build test quality'
+
+  -v, --version=version     version of the app
+  -h, --help                this helper
+  -t, --token=token         token to push releases
+  -W, --work-path=path      set working path, default is ./
+EOF
+
 
 echo_red() {
     echo >&2 -e "\033[0;31m${@}\033[0m"
@@ -16,14 +46,14 @@ echo_green() {
 
 gomake_update() {
     echo_green "Downloading gomake"
-    wget -q -O ${dir}/gomake.tmp https://raw.githubusercontent.com/n0rad/gomake/master/gomake
-    chmod +x ${dir}/gomake.tmp
-    mv ${dir}/gomake.tmp ${dir}/$0
+    wget -q -O ${work_path}/gomake.tmp https://raw.githubusercontent.com/n0rad/gomake/master/gomake
+    chmod +x ${work_path}/gomake.tmp
+    mv ${work_path}/gomake.tmp ${work_path}/$0
 }
 
 clean() {
     echo_green "Cleaning"
-    rm -Rf ${dir}/${target_name}
+    rm -Rf ${work_path}/${target_name}
 }
 
 build() {
@@ -36,23 +66,25 @@ build() {
     [ -f /usr/bin/upx ] || (echo "upx is required to build" && exit 1)
 
     echo_green "Save Dependencies"
-    godep save ./${dir}/... || echo "Cannot save dependencies. Continuing"
+    godep save ./${work_path}/... || echo "Cannot save dependencies. Continuing"
 
     IFS=',' read -ra current <<< "$osarchi"
     for e in "${current[@]}"; do
         echo_green "Building $e"
 
         GOOS="${e%-*}" GOARCH="${e#*-}" \
-        godep go build -ldflags "-X main.BuildTime=`date -u '+%Y-%m-%d_%H:%M:%S_UTC'` -X main.Version=${version}-`git rev-parse HEAD`" \
-            -o ${dir}/${target_name}/${app}-v${version}-${e}/${app}
+        $(cd ${work_path} && godep go build -ldflags "-X main.BuildTime=`date -u '+%Y-%m-%d_%H:%M:%S_UTC'` -X main.Version=${version}-`git rev-parse --short HEAD`" \
+            -o ${target_name}/${app}-v${version}-${e}/${app})
 
-        if [ "${e%-*}" != "darwin" ]; then
-            echo_green "Compressing ${e}"
-            upx ${dir}/${target_name}/${app}-v${version}-${e}/${app} &> /dev/null
+        if [ ${upx} ]; then
+            if [ "${e%-*}" != "darwin" ]; then
+                echo_green "Compressing ${e}"
+                upx ${work_path}/${target_name}/${app}-v${version}-${e}/${app} &> /dev/null
+            fi
         fi
 
         if [ "${e%-*}" == "windows" ]; then
-            mv ${dir}/${target_name}/${app}-v${version}-${e}/${app} ${dir}/${target_name}/${app}-v${version}-${e}/${app}.exe
+            mv ${work_path}/${target_name}/${app}-v${version}-${e}/${app} ${work_path}/${target_name}/${app}-v${version}-${e}/${app}.exe
         fi
     done
     echo_purple "Build duration : $((`date +%s`-${start}))s"
@@ -61,11 +93,12 @@ build() {
 
 install() {
     echo_green "Installing"
-    cp ${dir}/${target_name}/${app}-v${version}-$(go env GOHOSTOS)-$(go env GOHOSTARCH)/${app}* ${GOPATH}/bin/
+    cp ${work_path}/${target_name}/${app}-v${version}-$(go env GOHOSTOS)-$(go env GOHOSTARCH)/${app}* ${GOPATH}/bin/
 }
 
 quality() {
     start=`date +%s`
+    cd ${work_path}
 
     go_files=`find . -name '*.go' 2> /dev/null | grep -v ${target_name}/ | grep -v vendor/ | grep -v .git`
 
@@ -77,12 +110,12 @@ quality() {
 
     echo_green "Err check"
     [ -f ${GOPATH}/bin/errcheck ] || go get -u github.com/kisielk/errcheck
-    errcheck ./... | grep -v vendor
+    errcheck ./... | grep -v 'vendor/' | grep -v 'Close(' | grep -v '_test.go'
 
     echo_green "Lint"
     [ -f ${GOPATH}/bin/golint ] || go get -u github.com/golang/lint/golint
     for i in ${go_files}; do
-        golint ${i}
+        golint ${i} | grep -v 'should have comment ' || true
     done
 
     echo_green "Vet"
@@ -102,6 +135,7 @@ quality() {
     [ -f ${GOPATH}/bin/gocyclo ] || go get -u github.com/fzipp/gocyclo
     gocyclo -over 15 ${go_files} || true
 
+    cd -
     echo_purple "Quality duration : $((`date +%s`-${start}))s"
 }
 
@@ -157,7 +191,7 @@ release() {
     require_clean_work_tree
 
     echo_green "Compress release"
-    cd ${dir}/${target_name}
+    cd ${work_path}/${target_name}
     for i in *-* ; do
         if [ -d "$i" ]; then
             tar czf ${i}.tar.gz ${i}
@@ -172,7 +206,7 @@ release() {
 
     posturl=$(curl --data "{\"tag_name\": \"v${version}\",\"target_commitish\": \"master\",\"name\": \"v${version}\",\"body\": \"Release of version ${version}\",\"draft\": false,\"prerelease\": false}" https://api.github.com/repos/${github_repo}/releases?access_token=${access_token} | grep "\"upload_url\"" | sed -ne 's/.*\(http[^"]*\).*/\1/p')
 
-    for i in ${dir}/${target_name}/*.tar.gz ; do
+    for i in ${work_path}/${target_name}/*.tar.gz ; do
         fullpath=$(ls ${i})
         filename=${fullpath##*/}
         curl -i -X POST -H "Content-Type: application/x-gzip" --data-binary "@${fullpath}" "${posturl%\{?name,label\}}?name=${filename}&label=${filename}&access_token=${access_token}"
@@ -183,7 +217,7 @@ release() {
 test() {
     start=`date +%s`
     echo_green "Testing"
-    godep go test -cover ${dir}
+    godep go test -cover $(go list ${work_path}/... | grep -v vendor/)
 
     echo_purple "Test duration : $((`date +%s`-${start}))s"
 }
@@ -193,84 +227,33 @@ test() {
 
 global_start=`date +%s`
 
-read -d '' helper <<EOF || true
-Usage: gomake [-v version][-t token] command...
-
-  command...                commands to run among clean, build, quality, test, release, gomake_update
-                            default is : 'clean build test quality'
-  -v, --version=version     version of the app
-  -h, --help                this helper
-  -t, --token=token         token to push releases
-EOF
-
-target_name=dist
-dir=$( dirname "$0" )
-full_dir=$(cd "${dir}"; pwd)
-app=$(basename ${full_dir})
-repo=$(git config --get remote.origin.url | sed -n 's/.*@\(.*\)\.git/\1/p' | tr : /)
-osarchi="$(go env GOHOSTOS)-$(go env GOHOSTARCH)"
-release_osarchi="linux-amd64,darwin-amd64,windows-amd64"
-version=0
-access_token=
-
-if [ -f ${dir}/gomake.cfg ]; then
- . ${dir}/gomake.cfg
-fi
-
 commands=()
 while [ $# -gt 0 ]; do
     case "${1}" in
-        -h|--help)
-            echo "${helper}"
-            exit 0
-            ;;
-        --version=*)
-            version="${1#*=}"
-            shift
-            ;;
-        --token=*)
-            token="${1#*=}"
-            shift
-            ;;
-        -v)
-            version="${2}"
-            [ $# -gt 1 ] || (echo_red "Missing argument for version"; exit 1)
-            shift 2
-            ;;
-        -t)
-            token="${2}"
-            [ $# -gt 1 ] || (echo_red "Missing argument for token"; exit 1)
-            shift 2
-            ;;
-        --)
-            shift
-            commands+=("${@}")
-            break
-            ;;
-        *)
-            commands+=("${1}")
-            shift
-            ;;
+        -h|--help)  echo "${helper}"; exit 0;;
+        --version=*)version="${1#*=}"; shift;;
+        --token=*)  token="${1#*=}"; shift;;
+        --work-path=*) work_path="${1#*=}"; shift;;
+        -v)         version="${2}"; [ $# -gt 1 ] || (echo_red "Missing argument for ${1}"; exit 1); shift 2;;
+        -t)         token="${2}"; [ $# -gt 1 ] || (echo_red "Missing argument for ${1}"; exit 1); shift 2;;
+        -W)         work_path="${2}"; [ $# -gt 1 ] || (echo_red "Missing argument for ${1}"; exit 1); shift 2;;
+        --)         shift; commands+=("${@}"); break;;
+        *)          commands+=("${1}"); shift;;
     esac
 done
 
+if [ -f ${work_path}/gomake.cfg ]; then
+ . ${work_path}/gomake.cfg
+fi
 
 if [ ${#commands[@]} -eq 0 ]; then
     commands=(clean build test quality)
 fi
-
 command_count=0
 for i in "${commands[@]}"; do
     case ${i} in
-        test|build|release|clean|quality|gomake_update)
-            ${i}
-            ((++command_count))
-        ;;
-        *)
-            echo_red "Unknown command '${i}'"
-            echo ${helper}
-            exit 1
-        ;;
+        test|build|release|clean|quality|gomake_update) ${i}; ((++command_count));;
+        *)                                              echo_red "Unknown command '${i}'"; echo ${helper}; exit 1;;
     esac
 done
 
